### ISSUE TITLE
FromStr and Deref

### ISSUE THREAD

**Issue by killercup** [kevincox/humanbool.rs#1]
I think you could make a newtype wrapper around `bool` and implement `FromStr` (with your custom error type) and `Deref` (to get a bool and call boolean methods) on it.

**Comment by kevincox** [comment]
I see what you are saying but don't really see the advantage. Is it so that the imported function are scoped rather then global?

**Comment by killercup** [comment]
The advantage I was thinking of is that you don't need to introduce (and document and learn) any functions at all: You just implement well-known traits that are part of `std`. Any code that already uses `FromStr` can just include this crate and benefit from it.

Basically, your `parse` function does the same as `from_str`.

**Comment by kevincox** [comment]
Yeah, I see your point. That sounds like a good idea. 

However I'm wondering if there are many situations where those traits would be used "silently" as I don't want to hijack all the strings in the users code.

**Comment by killercup** [comment]
I don't think that's possible – you always need to specify the type you want to convert your string to.

Assuming you impl FromStr for a type `struct HumanBool(bool)`, you need to write `HumanBool::from_str("y")`. If you also `impl Deref for HumanBool` with `Target = bool`, you can then `let answer = *HumanBool::from_str("y");`. (I didn't test this, though.)

**Comment by kevincox** [comment]
Ah yes. That makes sense. Ok, I'll add those traits when I get the chance.
Or if you have time feel free to send a PR.

**Comment by kevincox** [comment]
I have implemented this in #2 but I'm not convinced of the utility. Can you show an example where this makes code cleaner/possible to write?

**Comment by kevincox** [comment]
@killercup I have implemented this in #2 but I'm not convinced of the utility. Can you show an example where this makes code cleaner/possible to write?

**Comment by killercup** [comment]
I don't have an example right now, but IIRC this would make it possible to use trait bounds (using FromStr), which I would consider idiomatic Rust to abstract over ways to get a value of some type. It's a bit weird though, as you'd not get a bool but a newtype of a bool. BTW, if you were to go this route, I'd probably also `impl From<HumanBool> for bool`.

In the end, though, this might be more trouble than it's worth.

**Comment by kevincox** [comment]
> In the end, though, this might be more trouble than it's worth.

This is what I'm thinking. I'll close this and the PR but keep the code around so that if a use case comes up it is already done.
